name: edu_sign
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Diperbarui untuk kompatibilitas yang lebih baik

dependencies:
  flutter:
    sdk: flutter

  # Menggunakan versi Firebase yang sudah terbukti stabil untuk web
  firebase_core: 2.15.1
  firebase_auth: 4.9.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # Versi umum yang kompatibel

flutter:
  assets:
    - assets/images/logo.png

  uses-material-design: true